kind: pipeline
type: docker
name: default
trigger:
  branch:
    - master

steps:
- name: Build
  image: node
  commands:
  - yarn
  - yarn export
- name: Upload 
  image: node
  commands:
  - eval `ssh-agent -s`
  - echo "$SSH_KEY" | ssh-add -
  - mkdir -p ~/.ssh
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  - rsync -rv -e "ssh -p 22" /drone/src/build/ drone@localhost:/var/www/linwood/ --checksum
  environment:
    SSH_KEY:
      from_secret: drone_ssh_key